exports.exampleStructured = { id: 'CPQwvlRQVLV_UqXGmfkeGlTj02eOgLhr',
  title: 'Knowt: The Ideas Platform',
  contents: 
   [ { id: 'Hx3m3N8REMuuUKtGUovjWjCf2RMyY4c4',
       type: 'header',
       content: '',
       children: 
        [ { id: 'pCCXcXKCJjLlJciCaRKdl32XTcsNnAiN',
            type: 'body',
            content: 'For the last 30 years, document editing software has remained almost exactly the same: text, tables, and images are layed out on a virtual page, with a dizzying array of layout and formatting options getting between you, and the document you want write.' },
          { id: 'OV4k4n_W3hSh_fhm2BW_p9A1usIkwzi_',
            type: 'header',
            content: 'Knowt wants to change that in 3 main ways:',
            children: 
             [ { id: 's5AFObkWuSwCXLYvQSSgfSSzI2qhG4Ag',
                 type: 'header',
                 content: 'Arrested Development',
                 children: 
                  [ { id: 'ppMpKH0qDFGO7tLgTGbS0qs1nvZQ39fY',
                      type: 'body',
                      content: 'I know what an erection feels like, Michael. There\'s a girl in my soup!' },
                    { id: 'udv2doHV59lHZLAXaFIrT2BjY1hkw05m',
                      type: 'body',
                      content: 'If I look like a man who made love to his wife last night – it\'s because I almost did. Actually, that was a box of Oscar\'s legally obtained medical marijuana. Primo bud. Real sticky weed. And THAT\'S why you always leave a note. You might enjoy this. Oh. Em. Gee. That\'s amazing.' },
                    { id: 'rIMOVm0Hj_QBPkI8mTFCWQqEyGX0oMzj',
                      type: 'body',
                      content: 'Hola, is Rosa still alive? No? Well this is not my day. Operation Hot Mother. Everybody dance NOW. Mister gay is bleeding! Mister gay! What\'s gotten into you? Have you been eating cheese? Hahahahah! Uncle Gob, was Aunt Lindsay ever pregnant? Yeah, sure, dozens of times. ♪♪ Big yellow joint, big yellow joint, I\'ll meet you down at the big yellow joint. ♪♪ I\'m a complete failure. I can\'t even fake the death of a stripper.' },
                    { id: 'u69_9aKiUZRYotOyUCZfxPYbXWUd8b99',
                      type: 'body',
                      content: 'Hey, maybe you could pop a tent outside with your cousin Maeby… it\'d be a good chance to rub off on her. Let\'s make Ann the backup, okay? Very good way to think about her, as a backup. Tobias Fünke costume. Well, Michael, I did not find their buffoonery amusing. She calls it a Mayonegg. "Circumvent." It means "to go around." Gob: The old "reach around." ' } ] },
               { id: 'lNRZNbF1ApnES_lsARLVPjwudtRI82lj',
                 type: 'header',
                 content: 'Skating',
                 children: 
                  [ { id: 'mKUm5MurTITpjKdxjSvs6swSplioRrXj',
                      type: 'body',
                      content: 'Kevin Jarvis finger flip boardslide tail stalefish 50-50 full pipe disaster. Street mute-air hang-up kingpin gnar bucket aerial bigspin. Ollie hole tic-tac carve switch transfer risers wheels Mark Gonzales. Pressure flip Kevin Harris indy grab yeah sketchy bail bank. Vert invert slam bruised heel switch bearings hard flip. Betty dude frigid air nose slide slam Rodney Mullen camel back tail. Tailslide 540 crail grab Pantsman 50-50 manual stalefish speed wobbles. Launch ramp baseplate pressure flip Agent Orange ollie north spine helipop crail slide. Sean Cliver downhill acid drop tailslide nosepicker ho-ho kingpin body varial.' },
                    { id: 'SuVcrHbHScyUdjY95VU4GZeg5bNvAx6o',
                      type: 'body',
                      content: '360 griptape late frontside flail fakie hand rail. Poseur slide cess slide judo air pump wax sponsored. Pressure flip coffin 900 cab flip manual crail grab indy grab. Full-cab casper crail slide g-turn deck front foot impossible Ron Allen full pipe. Crail grab boned out Tony Magnusson slap maxwell sick method air egg plant regular footed. Coffin rails lien air nollie nose bump casper slide Brooklyn Banks frigid air. Death box method air axle pop shove-it Lance Mountain slide street flail. Death box axle nollie method air flail air salad grind. Crooked grind nosebone blunt rails vert heel flip steps. Full pipe fakie out no comply regular footed durometer half-cab skater. Wax grind layback kickflip Santa Monica Airlines quarter pipe stalefish vert.' },
                    { id: 'Ob3Zv_lgIsbHYYTn7AwS9KPsJAIJ63kc',
                      type: 'body',
                      content: 'Impossible 50-50 mini ramp half-cab bigspin. Fakie slob air 720 hip bail. Late ho-ho Kevin Staab shoveit nose-bump slap maxwell. Frigid air dude hang up Skateboarder full pipe hang-up. Fakie out quarter pipe rail slide coffin pool. Sketchy bluntslide shoveit coper snake. Fast plant Tracker hospital flip opposite footed backside. Stalefish 720 fast plant switch Primo slide Rat Bones. Death box gap Video Days regular footed transfer casper slide. Kickflip shinner front foot impossible rad wax. Half-cab pool stalefish aerial body varial. Lip ollie opposite footed skater crooked grind. Hard Corps pool risers hand rail durometer bigspin. ' } ] },
               { id: 'By6q_DrTTGiJgiRwWAiRjRogjY7iDuhV',
                 type: 'header',
                 content: 'And Hipster Bullshit',
                 children: 
                  [ { id: 'I4cq9Z0_jSgTYL3qfKOcHz63TImwjRIv',
                      type: 'body',
                      content: 'astropub tote bag vegan, sustainable tacos neutra PBR&B. Kinfolk mlkshk aesthetic migas mumblecore asymmetrical. Readymade 8-bit cornhole, paleo aesthetic truffaut heirloom. Ugh squid yuccie, chicharrones church-key shabby chic jean shorts. Occupy bushwick hoodie, kogi single-origin coffee health goth bicycle rights sustainable jean shorts pickled kombucha drinking vinegar food truck disrupt. Cronut gentrify yuccie tumblr mustache etsy biodiesel, ugh knausgaard leggings 8-bit four dollar toast waistcoat stumptown wolf. Cliche echo park celiac four loko hashtag.' },
                    { id: 'VFMIYNkIbUZjKcxSAlVIIjTAcRxo5Fu4',
                      type: 'body',
                      content: 'Williamsburg DIY whatever affogato, heirloom cred raw denim. Shabby chic chambray post-ironic raw denim 8-bit offal. Helvetica blog gastropub, single-origin coffee kogi meggings authentic trust fund selvage tousled vice listicle humblebrag XOXO organic. Offal bespoke kale chips, shoreditch knausgaard cliche flannel chambray 3 wolf moon celiac tofu cray drinking vinegar tacos keffiyeh. Brooklyn occupy 3 wolf moon wolf keytar. Heirloom listicle lumbersexual, fingerstache semiotics art party humblebrag gastropub flannel. Biodiesel ethical iPhone seitan yuccie, PBR&B taxidermy everyday carry put a bird on it twee brooklyn salvia offal occupy scenester.' },
                    { id: 'fkW6vimn9OXqfMMXT_qVrGmwfJmx0iZF',
                      type: 'body',
                      content: 'Occupy kale chips cardigan ugh letterpress deep v intelligentsia. Farm-to-table mumblecore stumptown, kale chips pug tousled gastropub health goth vegan beard selvage humblebrag. Meh butcher organic selfies, cardigan chambray photo booth skateboard literally occupy gastropub health goth asymmetrical master cleanse humblebrag. Pabst viral sriracha, you probably haven\'t heard of them before they sold out next level neutra cold-pressed scenester schlitz affogato roof party migas. Bushwick slow-carb literally post-ironic pour-over small batch. Chambray meditation farm-to-table chicharrones selfies. Kale chips actually cronut gochujang, tumblr offal fashion axe scenester.' } ] },
               { id: 'JQ0Ha3fj2yLT5OsDiBi8ohHZDAMMjXag',
                 type: 'body',
                 content: 'For more information about knowt, please visit [codogo.io](https://www.codogo.io) or email [team@codogo.io](mailto:team@codogo.io)' } ] } ] } ] }
